export enum StatusBecomeSupplier{
    PEDDING="PEDDING",
    REVEICED="REVEICED",
    PROCESSING="PROCESSING",
    REQUIRED_ADDITIONAL_INFO="REQUIRED_ADDITIONAL_INFO",
    WAITING_FOR_APPROVCE="WAITING_FOR_APPROVCE",
    APPROVED="APPROVED",
    REJECT="REJECT",
    COMPLETE="COMPLETE",
    CANCEL="CANCEL",
    DRAFT="DRAFT"
}